### ISSUE TITLE
Subscriber can't receive data when msg data is bigger than 64K.

### ISSUE THREAD

**Issue by kelebujiabing** [davidhodo/idl_msgs#2]
hi, I have gen a sensor_msgs::msg::PointCloud2 type msg from ROS2 PointCloud2.idl.  When i fill msg.data beyong about 64Kb, the subscirber can't call the function onNewDataMessage even matched.

Publisher from ROS2 node: 

    auto message = sensor_msgs::msg::PointCloud2();
    message.header.stamp.nanosec = 637346029;
    message.header.stamp.sec = 1599623990;
    message.header.frame_id = "lidar";
    message.point_step = 32;
    message.row_step = 57600;
    message.is_dense = false;
    int size = message.height * message.width ;
    int k=64;
    message.data.resize(k*1024);
    for(int i=0; i<k*1024; i++)
    {
      message.data[i] = i;
    }
    RCLCPP_INFO(this->get_logger(), "Publishing points");
    publisher_->publish(message);

Subscriber from fastrtps:

    ParticipantAttributes PParam;
    PParam.rtps.builtin.domainId = 0; //MUST BE THE SAME AS IN THE PUBLISHER
    PParam.rtps.builtin.leaseDuration = c_TimeInfinite;
    PParam.rtps.listenSocketBufferSize = 4194304;
    PParam.rtps.sendSocketBufferSize = 1048576;
    PParam.rtps.setName("point_subscriber"); //You can put the name you want
    mp_participant = Domain::createParticipant(PParam);

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    SubscriberAttributes Rparam;
    Rparam.topic.topicKind = NO_KEY;
    Rparam.topic.topicDataType = myType.getName(); //Must be registered before the creation of the subscriber
    Rparam.topic.topicName = "rt/rslidar_points";
    mp_subscriber = Domain::createSubscriber(mp_participant,Rparam, static_cast<SubscriberListener*>(&m_listener));

    std::cout << "Subscriber created of type: " << Rparam.topic.topicDataType << " on topic: " 
        << Rparam.topic.topicName << std::endl;

here is the print of subscriber and publisher:

![20200910172819](https://user-images.githubusercontent.com/10735902/92711991-a1df6f80-f38b-11ea-9bba-a7aff968550f.png)
![20200910172851](https://user-images.githubusercontent.com/10735902/92711995-a2780600-f38b-11ea-9668-b42cbb66bd6f.png)

pls help! thanks a lot.

**Comment by WeekendWar** [comment]
Looks like this may apply, if you haven't tried it already. https://fast-dds.docs.eprosima.com/en/v1.8.3/advanced.html#sending-large-data

**Comment by kelebujiabing** [comment]
> Looks like this may apply, if you haven't tried it already. https://fast-dds.docs.eprosima.com/en/v1.8.3/advanced.html#sending-large-data

Thanks for reply. 
Yes, I have read the doc. But it just tell how to publish a big data message rather than subscribe.
And I found ROS2's History memory policy is: PREALLOCATED_WITH_REALLOC_MEMORY_MODE  .https://github.com/ros2/rmw_fastrtps/blob/master/README.md
next , I add this parameter in SubscriberAttributes:

Rparam.historyMemoryPolicy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;

it works.
